# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NLT Robotica HAVO
author: Joost van Tiel
logo: logo.png
copyright: "2026 'NLT Robotica' by Joost van Tiel is licensed under CC BY-NC-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/"

sphinx:
  config:
    html_show_copyright: true


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
#latex:
#  latex_documents:
#    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/JoostvanTiel/NLT-Robotica-HAVO  # Online location of your book
  path_to_book: .  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  extra_footer: |
    <p>
        <a href="https://joostvantiel.github.io/NLT-Robotica-HAVO/intro.html">NLT Robotica</a> Â© 2026 by <a href="https://github.com/JoostvanTiel/">Joost van Tiel</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;">
    </p>
  use_issues_button: true
  use_repository_button: true